import AccordianMenuVue from './base/AccordianMenu.vue';
import BaseButtonVue from './base/BaseButton.vue';
import BaseDialogVue from './base/BaseDialog.vue';
import BaseIconButtonVue from './base/BaseIconButton.vue';
import BaseSearchVue from './base/BaseSearch.vue';
import CheckboxInputVue from './base/CheckboxInput.vue';
import DatePickerVue from './base/DatePicker.vue';
import InputNumberVue from './base/InputNumber.vue';
import InputPasswordVue from './base/InputPassword.vue';
import InputRadioVue from './base/InputRadio.vue';
import InputTelVue from './base/InputTel.vue';
import InputTextVue from './base/InputText.vue';
import InputTextareaVue from './base/InputTextarea.vue';
import MultiSelectVue from './base/MultiSelect.vue';
import SingleSelectVue from './base/SingleSelect.vue';
import MultipleSelectVue from './base/MultiSelect.vue';
import GenderRadioGroupVue from './base/GenderRadioGroup.vue';
import SearchInputVue from './SearchInput.vue';
import TableHeaderVue from './TableHeader.vue';
import AvatarFormVue from './AvatarForm.vue';
import ProfileItemVue from './ProfileItem.vue';
import ProfileItemInfoVue from './ProfileItemInfo.vue';
import ProfileItemCardVue from './ProfileItemCard.vue';
import ProfileItemStudentCardVue from './ProfileItemStudentCard.vue';
import ProfileAvatarVue from './ProfileAvatar.vue';
import PieChartVue from './PieChart.vue';
import DegreeSelectVue from './DegreeSelect.vue';
import ToastUICalendarVue from './calendar/ToastUICalendar.vue';
import TimePickerVue from './base/TimePicker.vue';
import AutoCompleteBaseVue from './base/AutoCompleteBase.vue';
import SearchFormVue from './SearchFormBase.vue';
import BaseGroupCheckboxVue from './base/BaseGroupCheckbox.vue';
import LoadingOverlayVue from './LoadingOverlay.vue';
import TableBaseVue from './TableBase.vue';
import SortTableColumnHeaderVue from './base/SortTableColumnHeader.vue';
import BaseSettingDialogVue from './base/BaseSettingDialog.vue';
import BaseCircleIconVue from './base/BaseCircleIcon.vue';
import ColorPickerVue from './base/ColorPicker.vue';
import CollapseListVue from './CollapseList.vue';
import BaseButtonLinkVue from './base/BaseButtonLink.vue';
import ProfileEmailVue from './ProfileEmail.vue';
import ProfileRecordingsVue from './ProfileRecordings.vue';
import InputStatusVue from './base/InputStatus.vue';
import VideoPlayerVue from './VideoPlayer.vue';
import EllipsisTableDataVue from './base/EllipsisTableData.vue';
import BaseInputFileVue from './base/BaseInputFile.vue';
import ActionIconVue from './ActionIcon.vue';

export const AccordianMenu = AccordianMenuVue;
export const BaseButton = BaseButtonVue;
export const BaseDialog = BaseDialogVue;
export const BaseIconButton = BaseIconButtonVue;
export const BaseSearch = BaseSearchVue;
export const CheckboxInput = CheckboxInputVue;
export const DatePicker = DatePickerVue;
export const InputNumber = InputNumberVue;
export const InputPassword = InputPasswordVue;
export const InputRadio = InputRadioVue;
export const InputTel = InputTelVue;
export const InputText = InputTextVue;
export const InputTextarea = InputTextareaVue;
export const MultiSelect = MultiSelectVue;
export const SingleSelect = SingleSelectVue;
export const MultipleSelect = MultipleSelectVue;
export const GenderRadioGroup = GenderRadioGroupVue;
export const SearchInput = SearchInputVue;
export const TableHeader = TableHeaderVue;
export const AvatarForm = AvatarFormVue;
export const ProfileItem = ProfileItemVue;
export const ProfileItemInfo = ProfileItemInfoVue;
export const ProfileItemCard = ProfileItemCardVue;
export const ProfileItemStudentCard = ProfileItemStudentCardVue;
export const ProfileAvatar = ProfileAvatarVue;
export const PieChart = PieChartVue;
export const DegreeSelect = DegreeSelectVue;
export const ToastUICalendar = ToastUICalendarVue;
export const TimePicker = TimePickerVue;
export const BaseAutoComplete = AutoCompleteBaseVue;
export const SearchForm = SearchFormVue;
export const BaseGroupCheckbox = BaseGroupCheckboxVue;
export const SortTableColumnHeader = SortTableColumnHeaderVue;
export const BaseSettingDialog = BaseSettingDialogVue;
export const LoadingOverlay = LoadingOverlayVue;
export const TableBase = TableBaseVue;
export const CircleIcon = BaseCircleIconVue;
export const ColorPicker = ColorPickerVue;
export const CollapseList = CollapseListVue;
export const BaseButtonLink = BaseButtonLinkVue;
export const ProfileEmail = ProfileEmailVue;
export const InputStatus = InputStatusVue;
export const VideoPlayer = VideoPlayerVue;
export const ProfileRecordings = ProfileRecordingsVue;
export const EllipsisTableData = EllipsisTableDataVue;
export const BaseInputFile = BaseInputFileVue;
export const ActionIcon = ActionIconVue;
